### ISSUE TITLE
Viewing an image in a post shows the description text with HTML markup

### ISSUE THREAD

**Issue by lgp171188** [e14n/pump.io#1023]
![identica_bug](https://cloud.githubusercontent.com/assets/218870/3170097/233ed566-ebaf-11e3-9487-7b56e8b2db1b.PNG)

Please see the screenshot for understanding this issue. The description is shown with HTML markup though the user didn't enter any HTML markup in the description

**Comment by larjona** [comment]
Closing, it will be handled in #640
