### ISSUE TITLE
Warning box does not disappear after logging in

### ISSUE THREAD

**Issue by mehdisadeghi** [e14n/pump.io#1055]
I just installed pump.io using `sudo npm -g install pump` on my Ubuntu 14.04 server and registered my first user on the website. I got an error dialog box telling me that my password should be longer and so on. After giving a better password and logging in I see the error message is still there and has not disappeared and needs a page refresh to go away. Just wanted to record it here.

**Comment by strugee** [comment]
@mehdisadeghi why did you close this? Can you no longer reproduce this issue?

**Comment by mehdisadeghi** [comment]
@strugee I don't have a pump.io installation at the moment and nobody else has commented during the last two years (including myself). Therefore I closed this, because it seemed irrelevant issue to me. Feel free to reopen if you experience the same error.

**Comment by strugee** [comment]
Okay. I think this is a duplicate of #1133 anyway, so I'll just leave this closed.
