### ISSUE TITLE
TLS state-of-the-art in pump.io. We need to progress!

### ISSUE THREAD

**Issue by luisgf** [e14n/pump.io#1061]
Hi Evan:

I open this issue with the aims to make evolu the state-of-the-art in pump.io security. 

By default pump.io in its standalone mode has a wrong and terrible TLS configuration that  don't follow the latests good practices. The security and privacy of the users is primordial for me, and for that I wrote this patch that aims to help with that.

The patch implement the following:

-  SSLv3 protocol deactivation to prevent POODLE attack
- Improve cipher strength disabling weak ciphers and prefer DHE,EDHE ciphers when nodejs 0.12.x arrive. 
- Enable SSL session resumption. This boost the TLS session resume and performance overall.
- Disable TLS client renegotiation

And here, a small list the would be nice to be in the TODO list.

Desirable:
- DANE support
- Forbid connections to pump servers with weak RSA keys (<=1024 bits)
- Support for Nodejs v0.12.x. This is necessary in order to support Forward Secrecy.
- Disallow access via HTTP Plain!!! Only support the creation of HTTPS servers. Its mandatory for any protocol by IETF since a few years ago

Please evan, be aware of the patch and help us to protect our users.

PS.- Edited for fix typos.

**Comment by stevenroose** [comment]
Is @evanp still working on pump.io?

**Comment by dper** [comment]
If Pump itself doesn't get these types of improvements, this creates incentive for more users to put it behind Nginx, which is something the documentation recommends against.

**Comment by shtrom** [comment]
A side problem is also trust of certificates #786

**Comment by strugee** [comment]
Closing as this is a super broad issue.

Better cipher suites just got merged into master. You'll need at least Node 0.12 to get decent ones, however.

I'll file followups for the remaining issues.
