### ISSUE TITLE
unable to set up pump.io

### ISSUE THREAD

**Issue by toomu** [e14n/pump.io#1077]
I have installed pump.io globally but am unable to set it up. There is no /etc/pump.io.json config file that was created. I have nodejs installed in home folder. Is it similar to mean/express modules that generate project files on initializing the project? pumpio documentation isn't clear about this.

**Comment by jfrobbins** [comment]
there is a pump.io/pump.io.json.sample that needs to be renamed.
https://github.com/e14n/pump.io/blob/master/pump.io.json.sample

there are more configuration specifics in the readme:
https://github.com/e14n/pump.io/blob/master/README.md

**Comment by strugee** [comment]
Closing given that an answer has been provided and there hasn't been activity in this issue in many months.
