### ISSUE TITLE
spanish home

### ISSUE THREAD

**Issue by mama21mama** [e14n/pump.io#1097]
[![imagebin](http://pumpio.ml/uploads/mama21mama/2015/8/12/On420g.png)](http://pumpio.ml/uploads/mama21mama/2015/8/12/On420g.png)

:+1:

**Comment by strugee** [comment]
What exactly do you want here? Nobody can tell.

**Comment by larjona** [comment]
@mama21mama I think it's better if you add your server in the wiki page https://github.com/e14n/pump.io/wiki/Community#people-running-a-public-pump-node-open-registration and close this issue.
Thanks for supporting the federated social network!

**Comment by larjona** [comment]
Closing this issue.
