### ISSUE TITLE
Read me does not contain instructions on running server

### ISSUE THREAD

**Issue by h4ck3rm1k3** [e14n/pump.io#1110]
The readme does not contain instructions on setting up a server.

**Comment by larjona** [comment]
Thanks for caring. Do you mind to point out the specific parts of installation that you miss? 
That could help us enhance the existing documentation. 

Currently, the README file ( https://github.com/e14n/pump.io/blob/master/README.md ) includes an "Installation" section including these subsections: Prerequisites, Install with npm, Local install, Database setup, Configuration, Web server proxy.

An idea could be to include a link "More info" pointing to the canonical source of pump.io documentation (currently, https://github.com/e14n/pump.io/wiki ) which includes some pages about installing and running a server (general, and for specific operative systems).


By the way, any help on improving the documentation is welcome. Please have a look at https://github.com/e14n/pump.io/wiki/Community and the last meeting logs; and join us in the next meeting! (will be posted in the Community wiki page and informed via the pump account https://pumpit.info/pumpio ).

**Comment by h4ck3rm1k3** [comment]
Yes I am working on setting up a server and will document it.
Well we need a step by step list of steps, config files to edit , etc.

**Comment by h4ck3rm1k3** [comment]
see #1114

**Comment by larjona** [comment]
Thanks @h4ck3rm1k3 for your contributions!!
We're also beginning a new documentation section, for system administrators.
The current documents are here: https://pumpio.readthedocs.org/en/latest/
and those documents are built from this repo: https://gitlab.com/pump.io/pump-docs
Now that your PR is merged, do you think this issue can be closed? I'm not sure if further info for sysadmins should go to the README or to the documentation repo.
