### ISSUE TITLE
"No such index 'dialbackrequest:' in '_databank_keys' with key 'dialbackrequest'"

### ISSUE THREAD

**Issue by h4ck3rm1k3** [e14n/pump.io#1124]
"No such index 'dialbackrequest:' in '_databank_keys' with key 'dialbackrequest'"

is that normal?

Error:
id: "dialbackrequest"
item: "dialbackrequest:"
message: "No such index 'dialbackrequest:' in '_databank_keys' with key 'dialbackrequest'"
name: "NoSuchItemError"
stack: undefined
type: "_databank_keys"

**Comment by strugee** [comment]
We need _way_ more information than what you've provided to diagnose this.

Post the full logs from the commandline. Tell us in what context the error occurs. What Databank driver are you using?

**Comment by h4ck3rm1k3** [comment]
this was memcached, In fact I have abandonded it because it was refusing connections after a while. switchd to mongo.
