### ISSUE TITLE
Adding jscs (JavaScript Code Style) to the devDependencies

### ISSUE THREAD

**Issue by profOnno** [e14n/pump.io#1137]
Feature request

Adding [JavaScript Code Style](http://jscs.info/) to the development tools.

The [HACKING.md](https://github.com/e14n/pump.io/blob/master/HACKING.md) describes the Code Style, and the [idiomatic style](https://github.com/jscs-dev/node-jscs/blob/master/presets/idiomatic.json) is available in the package. I am using this [Gist](https://gist.github.com/profOnno/3cd73649ea41804d9bfc) to get the e14n exceptions in the rules.

```javascript
{
    "preset": "idiomatic",
    "validateIndentation": 4,
    "disallowTabs": true,
    "requireSpacesInsideParentheses": null,
    "disallowSpacesInsideParentheses": null,
    "requireSpacesInsideBrackets": null,
    "disallowSpacesInsideBrackets": true,
    "requireSpacesInsideObjectBrackets": null,
    "requireCamelCaseOrUpperCaseIdentifiers": null,
    "requireCurlyBraces": null,
    "maximumLineLength": {
        "value": 120,
        "tabSize": 4,
        "allExcept": ["urlComments", "regex"]
    },  
    "requireSpaceBeforeBinaryOperators": [
        "=", "+=", "-=", "*=", "/=", "%=", "<<=", ">>=", ">>>=",
        "&=", "|=", "^=", "+=",
                
        "-", "*", "/", "%", "<<", ">>", ">>>", "&",
        "|", "^", "&&", "||", "===", "==", ">=",
        "<=", "<", ">", "!=", "!=="
    ],
    "requireSpaceAfterBinaryOperators": null
}   
```

The [idiomatic style](https://github.com/jscs-dev/node-jscs/blob/master/presets/idiomatic.json) uses the [JQuery style](https://github.com/jscs-dev/node-jscs/blob/master/presets/jquery.json).

Travel back the road to check if the rules are already defined. Dereference rule with `null` or just overwrite the rule with a different rule.

**Comment by strugee** [comment]
@profOnno done! The rules are fairly lax right now since I didn't want to mess with too much of the codebase. We can tighten them up even more at a later time.

**Comment by strugee** [comment]
@evanp I did my best to preserve the existing codebase style; if anything's wrong, just say so.
