### ISSUE TITLE
Support for code of meritocracy

### ISSUE THREAD

**Issue by mrseth** [e14n/pump.io#1145]
Since the other issue was closed, I just wanted to say that I support the adoption of a code of meritocracy. 

And kudos to @jart for not caving in to neo-progressivism bullying on the other issue.

**Comment by evanp** [comment]
Hey, thanks for the great idea. But we're not doing this.

**Comment by evanp** [comment]
And, just to be clear: I don't believe, and never have believed, in meritocracy. It's a self-serving myth. Open Source software communities are almost always do-ocracies.

https://communitywiki.org/DoOcracy

Under no circumstances am I interested in enshrining the sham concept of meritocracy into the pump.io community or contributor process.
