### ISSUE TITLE
Commit 0c9053174850142ffe5bf8679b18c2e53f63b12d breaks access to uploaded images

### ISSUE THREAD

**Issue by mrvdb** [e14n/pump.io#1174]
https://github.com/e14n/pump.io/commit/0c9053174850142ffe5bf8679b18c2e53f63b12d causes an issue where uploaded images can only be viewed if the user is logged on.

See: https://status.qua.name/mrb/image/kBhsY7-zSbercr_Cqxe2sQ  for discussion

**Comment by strugee** [comment]
@mrvdb thanks for reporting this. I've been away for several weeks (hence the show response), but this is on the radar now. It'll be fixed before 1.0.0.

**Comment by strugee** [comment]
@mrvdb just fixed this in master. Thanks so much for taking the time to report a bug!
