### ISSUE TITLE
Implement DOMPurify-based XSS scrubber

### ISSUE THREAD

**Issue by strugee** [e14n/pump.io#1184]
Followup to #1169 because that issue was getting cluttered. This is here to track just the implementation.

List from cure53/DOMPurify#176:

- [x] Serve all pages with an HTML5 doctype
- [x] Serve a security error page to a blacklist of legacy browsers
- [x] Make sure there's nothing sensitive in the URL of the page
- [x] Make sure e.g. password forms aren't in the same page as user-submitted content
- [x] Scrub all content with DOMPurify (obviously)
- [x] Content Security Policy specifies that fonts and form submissions are restricted to the origin
- [x] Tests
- [x] Fall back to sanitize-html if Node is too old for DOMPurify

**Comment by strugee** [comment]
So, here's the issue: DOMPurify requires a DOM to work, and server-side, that means [jsdom][1]. The newest jsdom that works with Node.js 0.12 is `jsdom@3`, and that's not good enough for DOMPurify. I've looked into porting jsdom back to Node 0.12, and it's not going to happen based on https://github.com/tmpvar/jsdom/issues/1284#issuecomment-236302212 (that issue is unrelated, but the key part to note is the mention of unpolyfillable, aka implicitly untranspilable ES6 features that Node 0.12 won't have). DOMPurify might use ES6 stuff too, but it doesn't matter anyway because jsdom doesn't work and will never work on 0.12.

So, here's what we're going to do, given the fact that we can't drop 0.12 support entirely (since so many distributions ship it):

1. Implement DOMPurify-based scrubbing on Node.js 4.x or better
2. Deprecate 0.12 support and throw up warnings every time the app is started under anything less than 4.x
3. Under 0.12, fall back to using the previous implementation based on `html-sanitizer` with the understanding that we cannot guarantee XSS protection in this scenario, and security is on a "best effort" basis

This is particularly unfortunate given the fact that we don't yet support Node 4.x in the same way we support 0.12 (i.e. tests don't run on 4.x yet) but we're in a tight situation with not a lot of good options, so this is the way it's going to be. The situation is only going to improve as more distros ship newer versions of Node, as we continue modernizing the dependency tree, and as we turn on test coverage for 4.x. Everything else will either break 0.12 support entirely or will have security problems and thus eventually require replacement anyway.

 [1]: https://github.com/tmpvar/jsdom

**Comment by strugee** [comment]
@larjona has convinced me on IRC that the above plan is too risky given how little 4.x testing we've done. So, we're now doing the above with the following modifications:

1. Running under Node 0.12 won't be deprecated, but we'll make it clear that we're planning to deprecate it in the near future
2. The README and release materials will include a notice explaining that Node 0.12 is going to be deprecated in the near future and that if the admin upgrades to 4.x early, they'll get better security but risk running into more bugs

**Comment by strugee** [comment]
The saga continues: apparently I misremembered and most Linux distros ship Node.js 0.10, not 0.12. So we're doing the same thing for 0.10 - it's not deprecated, but we're planning to deprecate it soon.

**Comment by strugee** [comment]
Also, since this issue will be linked in the change log, I should note that a bunch of security headers (which we should be sending anyway) are included as a side effect of the library we're using to build our Content Security Policy. This is a Good Thing™️.

**Comment by strugee** [comment]
This got merged to master yesterday.

**Comment by oshepherd** [comment]
Um, I looked through the changes here, and I can't see anywhere that you do client side scrubbing, but the web UI still fetches post content for display via proxy URLs?

So what you've implemented is a placebo: the minute you click the "view all comments" button, the web UI is vulnerable again.

This is one of the reasons I'm opposed to server-side scrubbing, BTW: because it's a false sense of security for client devs who have to deal with potentially malicious servers anyway.

**Comment by strugee** [comment]
@oshepherd good point, thank you. I'll file a follow-up.

WRT the decision, it was @evanp's decision, not mine (though I agree with him). It's worth noting that AS2 recommends XSS scrubbing. I also *think* this should be better in ActivityPub-land, but I'm not sure.

**Comment by oshepherd** [comment]
ActivityPub prohibits any form of message mangling as that would break message integrity features (such as the signature mechanism some people are working on)

**Comment by strugee** [comment]
@oshepherd no it doesn't. Probably some auth profiles will have that requirement but AP itself does not. And besides, there are ways to get around that - just do anti-XSS mangling _after_ signature validation.

/cc @cwebber
