### ISSUE TITLE
Like and favourite

### ISSUE THREAD

**Issue by xray7224** [e14n/pump.io#474]
This is simple and I don't want to sound like a pedant however, "like" and "favourite" do not mean the same and at least in the webUI they are seen as the same. When I click like on a notice it will show up as "Tsyesika favourited a note". Liking to me at least is very much i found it funny or enjoyed reading it some kind of positive view point on the note/image.

However just because I like something doesn't mean it's my favourite notes or one of my favourite. When see express that something is my favourite or one of my favourites it's of one the best I've seen. I'm not actually sure if we need to have both, I think it would be better to just change favourite to like throughout.

(this also could impact later when people translate the UI's of pump.io or pump clients as if there is not an expressed difference there may not be two words or if there is they might not be able to be used interchangeably)

**Comment by larjona** [comment]
Closing this in favour of #666
