### ISSUE TITLE
Can't access Register/Login from home pages in IE

### ISSUE THREAD

**Issue by TonyGravagno** [e14n/pump.io#571]
Go to pumpdog.me or pumpity.net with IE9. Click Register or Login. The first time this is done nothing happens. The second time it displays the page and then flashes back to the home page.Changing compatibility mode, etc doesn't help.

**Comment by larjona** [comment]
Internet Explorer 9 and 10 ended their life on 2016/01/12.
Closing this issue. If it's standing  for IE 11 or later, please open a new one.
Thanks!
