### ISSUE TITLE
If registration is disabled, don't offer to register

### ISSUE THREAD

**Issue by jpfleury** [e14n/pump.io#753]
The link *Get Started »* on the home page links to `/main/register`, like the link *New user?* on the page `/main/login`. If registration is disabled, the registration form should be replaced with a message explaining that this server is closed to registration, so users must find another one.

It wastes time to users that fill the registration form. They're notified that registration is disabled only after the registration form is correctly filled without any errors.

**Comment by larjona** [comment]
This is duplicated of #589, and it's already solved. Closing.
