### ISSUE TITLE
Incorrect results for addressee search

### ISSUE THREAD

**Issue by evanp** [e14n/pump.io#810]
Per @mray:

name completition seems to be broken.
looks like the first letter is always ignored.

Typing "ev" in the To-filed shows me "..Greve..." but not Evan.
and
"rod" shows me Prodromou while "Pro" shows me nothing.

https://identi.ca/mray/note/TJiolUvISUWZCds5ntbOZQ

**Comment by larjona** [comment]
Closing, it will be handled in #805
