### ISSUE TITLE
Activity description might have empty parts (in Meanwhile column, mainly)

### ISSUE THREAD

**Issue by jankusanagi** [e14n/pump.io#819]
A client can publish a **note** with the ***displayName*** property set to "" (empty string), which would result in something like **"JohnDoe posted a comment in reply to"**, without anything after "to", where something like **"a note"**, or a specific title for that note/picture/object should be.

While this is probably something the clients should avoid (setting the displayName property if it's empty), I guess pump.io should check for empty displayName's and treat them as "no displayName present".

This can be seen in the Meanwhile column or in notification e-mails, and can be caused, for instance, by older versions of Dianara, by posting an image with an empty title.

**Comment by strugee** [comment]
Closing as the corresponding PR was merged just under a year ago :)
