### ISSUE TITLE
User's feed doesn't show notes, which he (she) shared

### ISSUE THREAD

**Issue by yvolk** [e14n/pump.io#848]
I noticed that the note by AndStatus: https://identi.ca/andstatus/note/FvmhG0HWSDK4LXrG5eM4SQ
is shared by several users.
The note in JSON is here: https://identi.ca/api/note/FvmhG0HWSDK4LXrG5eM4SQ
I looked up feeds of the users who shared the note ( "/api/user/<username>/feed/"  the links are in the "activity-outbox" of the users listed as shares->items)
- no feeds have the note (with one exception...)!
So effectively the users didn't share the note: I guess their followers will not receive the shared note?!

Now about exceptions:
1. The only exception is "share" by the "yvolk" user (it's me :-) ) - yvolk's feed:
 DOES have the verb="share" activity ( see https://identi.ca/yvolk and https://identi.ca/api/user/yvolk/feed ). The difference from other users, who shared the same note, is the "generator": Yvolk shared the note using AndStatus client ( https://github.com/andstatus/andstatus/wiki ) which explicitly uses verb="share".
2. "Like" ("favorite") is an activity, similar to "share". But unlike "share" I DO see activities with verb="favorite": see the feeds of the users listed in the likes->items of the original note ( https://identi.ca/api/note/FvmhG0HWSDK4LXrG5eM4SQ ).

Hence effectively "like" works as "share" should work, and "shared" objects, unfortunately, don't propagate in user's output feed.

**Comment by jankusanagi** [comment]
You explained a lot of technical data that I don't think is necessary here.

The simple test: share someone else's note, go to your feed, see the shared note.

I've done this a million times, and it works. By default, sharing is done Cc: Followers, so looking at someone's feed via the webUI while logged out will NOT show those shares, but they're there for logged in followers to see.

**Comment by strugee** [comment]
Given @jankusanagi's comment, seems like we can close this. @yvolk if that doesn't seem like the solution, comment and I'll reopen. Thanks.
