### ISSUE TITLE
DtraceProviderBindings

### ISSUE THREAD

**Issue by timwhite8** [e14n/pump.io#884]
Hello,

I was trying to install and run pump.io on my Mac OS X in different ways (globally, locally etc), tried different versions of node but always experience the same issue:

Tims-MacBook-Air:pump.io Tim$ bin/pump
[Error: Symbol DTraceProviderBindings_module not found.]
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }

How does it affect application? How do I fix it?

**Comment by strugee** [comment]
Should be fixed in f49aa2ace85514d9472858d7068386c8e52c9507; if you still see this, comment and I'll reopen
